language: ruby
cache: bundler
rvm:
- 2.3.1
before_install:
  - gem update --system
  - gem install bundler
install:
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  strategy: git
  fqdn: apron.network
  local_dir: _site
  target_branch: main
  on:
    branch: develop
